apiVersion: v1
kind: ResourceQuota
metadata:
  name: team-quota
  namespace: default
spec:
  hard:
    requests.cpu: "6"
    requests.memory: 12Gi
    limits.cpu: "12"
    limits.memory: 24Gi
    requests.nvidia.com/gpu: "2"
    limits.nvidia.com/gpu: "2"
    pods: "20"
    services: "10"
    persistentvolumeclaims: "5"
